const recipes = [
    {
        title: 'Shrimp Scampi',
        description: "Shrimp Scampi is an amalgamation of many different traditional Italian preparations of scampi (otherwise known as langoustines, Dublin Bay prawns, or Norway Lobsters). Therefore, there isn’t one correct way in which to make it. Try swapping out the pasta in our recipes for rice, or even just a loaf of crusty bread.",
        ingredients: [
            '2 tsp kosher salt',
            '1/2 l linguine pasta',
            '3 Tbsp unsalted butter',
            '2 Tbsp oliv oil',
            '3 garlic cloves, crushed',
            '1/2 tsp crushed red pepper flakes',
            '1/2 cup dry white wine',
            '1 lb frozen shrimp defrosted and peeled',
            '1 tsp freshly ground black pepper',
            'Juice of 1 large lemon ',
            '2 Tbsp parsley, chopped',
        ],
        instructions: [
            'Fill a large pot ⅔  the way full with water and add 2 teaspoons of salt. Bring to a boil.',
            'Meanwhile, heat the butter and olive oil over medium-high heat in a large skillet.',
            'Once the butter is fully melted, add the crushed garlic and red pepper flakes. Cook until fragrant, about 30 seconds. ',
            'Add the pasta to the boiling water and cook until al dente according to the instructions on the box. ',
            'Add the wine to the skillet and cook until reduced by half, about 3-5 minutes. ',
            'Add the shrimp and cook on each side for about 45 seconds to 1 minute.',
            'Add the lemon juice and stir to incorporate',
            'Drain the pasta, but reserve ¼ cup of the water',
            'Add the pasta to the skillet and stir to combine. If the sauce looks separated, add the reserved pasta water.',
            'Season to taste and garnish with parsley.',
        ],
        imageURL: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Carbonara',
        description: "Carbonara has been the subject of some severe bastardization here in the states, where we regularly eschew Italian tradition in favor of garlic, bacon, and green peas for some reason. Today we're doing both the old-school and illegitimate versions of the hotly-contested dish, both of which deserve their place in your grandmother's handwritten recipe cards.",
        ingredients: [
            '1/2 pound guanciale',
            '3 large eggs',
            '1 egg yolk',
            '4 oz of Pecorino Romano',
            'Ground black pepper',
            'kosher salt',
            '16 oz spaghetti noodles',
            '1/4 cup starchy pasta water'
        ],
        instructions: [
            'Start by dicing ½ pound guanciale or pancetta. Set aside.',
            'In a large bowl or measuring cup, combine 3 large eggs and 1 egg yolk.',
            'Grate and measure out 4 ounces of cheese - I recommend Pecorino Romano or Parmigiano-Reggiano or a blend of the two.',
            'Combine grated cheese and eggs and beat together with a fork until homogenous.',
            'Season the egg and cheese mixture with fresh black pepper. Do not add salt yet, because the guanciale brings a lot of salt to the dish. Beat until well incorporated.',
            'Add the diced guanciale to a cold pan and then turn the heat to medium. This will allow the fat to render out slowly. Once it is fully cooked but not too crispy, turn off the heat.',
            'Add your noodles to a large pot of heavily salted water. Cook until they are to your desired texture.',
            'Add the cooked noodles to the pan with the guanciale. Toss to coat the noodles in the guanciale fat. ',
            'Work quickly to add the egg and cheese mixture to the pan and mix rigorously. This will help to emulsify the sauce and make it creamy. If it’s as smooth as you’d like, you can add a little bit of pasta water (about ¼ cup). Season with salt if it needs it.',
            'Plate up and enjoy! ',
        ],
        imageURL: 'https://images.unsplash.com/photo-1560434019-4558f9a9e2a1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Bolognese',
        description: "It doesn’t take a lot of ingredients (or a lot of money) to make a classic Bolognese recipe. What it does take, though, is patience for the sauce to achieve the ideal authentic texture. You’re going to go low and slow—it’ll take around 3 hours, but most of that cook time is hands-off.",
        ingredients: [
            '1 large onion, minced',
            '2 medium carrots, peeled and finely chopped',
            '3 ribs celery, finely chopped',
            '1 lb ground beef',
            '1 lb ground pork',
            '1 lb ground lamb (optional)',
            'Olive oil',
            '½ lb pancetta',
            '¼ cup tomato paste',
            '1 cup dry white wine',
            '32 oz chicken stock',
            '1 cup whole milk',
            'Bay leaves',
            'Parmesan cheese rinds (optional)',
            'Nutmeg, grated',
            'Kosher salt',
            'Freshly ground black pepper',
            '½ cup heavy cream',
            'Pappardelle pasta (if not made homemade)',
        ],
        instructions: [
            'Start by finely mincing 1 large onion, 2 peeled and finely chopped medium carrots, and 3 finely chopped ribs of celery. Set aside. ',
            'For the meats, in a large pot brown 1lb each of ground beef, pork, and lamb (optional) in some olive oil over medium heat until brown, 3-5 minutes. Place in a bowl and set aside. In a separate pan, dump ½ pound of pancetta and brown until the fat has rendered out and has become crispy. ',
            'In the same large pot, saute the onions with the finely chopped celery and carrots until soft. ',
            'Once the vegetables are soft and the pancetta is crisp, dump the pancetta into the pot with the vegetables along with ¼ cup of tomato paste. Mix to combine. ',
            'After 2 minutes of letting the tomato paste caramelize, pour in 1 cup of dry white wine (sauvignon blanc) and scraping up all the fond, and mixing together. Let simmer for about 5 minutes until the wine has almost completely evaporated.',
            'Add back in the browned beef, pork, and lamb to the pot and stir together. Once combined, ladle in 32 oz of the chicken stock. Just enough to submerge everything. ',
            'Top all of that with 1 cup of whole milk, 1 bay leaf (or 2), a couple of parmesan cheese rinds (optional), and grated nutmeg. Mix to combine.',
            'Place into a 300°F oven for 3-4 hours.',
            'Once the sauce is out of the oven and pasta is finished, skim off any excess fat from the sauce and remove the bay leaf from the pot. Taste for seasoning.',
            'Top with a generous amount of freshly grated parmesan, a generous pinch of kosher salt and freshly ground black pepper, and an optional ½ cup of heavy cream. Mix to combine.',
            'For final assembly, boil the pasta until just about done (45 seconds for fresh homemade pasta) and place it into a saucepan with a large amount of sauce along with ¼ cup of pasta water. ',
            'Toss together over medium-low heat until some of the sauce is absorbed and emulsified and the pasta is fully cooked.  ',
            'Place into a bowl for serving and enjoy.',
        ],
        imageURL: 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fHBhc3RhfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Braised Short Ribs',
        description: "Unbelievably delectable beef short ribs, slow cooked in wine and broth. Served over a bed of polenta, this is a seriously special dish!",
        ingredients: [
            '1 whole rack short ribs',
            '½ lb carrots, peeled and chopped',
            '5 stalks celery, chopped',
            '2 large onions, peeled and sliced',
            '1 Tbsp vegetable oil',
            '3 Tbsp tomato paste',
            '5 cloves garlic',
            'Soy sauce',
            '2 cups chicken stock',
            '2 cups amber ale (or red wine)',
            '½ cup prune juice',
            'Sprig thyme',
            'Sprig parsley',
        ],
        instructions: [
            'Start by removing the excess layer of skin and fat from the ribs. Season generously with kosher salt and freshly ground pepper on all sides. ',
            'Peel ½ pound of carrots and chop into manageable pieces. Cut the heads off a few stalks of celery and cut into manageable pieces. Peel and slice 2 large onions. ',
            'On the stovetop, heat a tablespoon of vegetable oil over medium-high heat until whisps of smoke emerge. ',
            'At which point, in batches, place the pieces of short rib into the pot and brown them on all sides. To prevent the fond from burning, place the ribs back down in the exact spot that they were before flipping. If exposed fond during the final batch, place a handful of onions to prevent the fond from burning. ',
            'Once every short rib is seared, add in the onions (or rest of the onions) and saute until soft and brown. Add in 3 tablespoons of tomato paste, sauteing and whisking together for an additional 2-3 minutes. ',
            'Add in the celery and carrots, sauteing to warm up, add in 5 cloves of garlic, 2 cups of an amber ale (or dry red wine), 2 cups of chicken stock, a splash of soy sauce, and ½ cup of prune juice. Stir to combine. ',
            'Add a few sprigs of fresh thyme and parsley.',
            'Nestle in the pieces of short rib making sure each piece peaks just above the liquid. Least browned side up.',
            'Cover and place into a 275°F oven for 4-5 hours. Check after 3.5 hours to check doneness. If there is no resistance after poking with a paring knife then the short ribs are done. ',
            'Once done, remove the short ribs from the pot and into the fridge (if made ahead of time) and strain the remaining solids out of the braising liquid. ',
            'If made for immediate use, let the liquid settle and skim the fat off the top of the liquid. ',
            'If made ahead of time, for a rapid cooling place a few big pieces of ice into the liquid and let sit for 15 minutes. Wrap with plastic wrap and place into the refrigerator for at least 4 hours and up to overnight. Once chilled, remove the solid layer of fat floating on top. ',
            'Once the fat is removed, boil the liquid in a high walled skillet until reduced by 80%. This can take 1-2 hours. ',
            'Once the sauce coats the back of a spoon, place the short ribs into the skillet and base with the sauce before covering and letting it sit for 20 minutes. ',
        ],
        imageURL: 'https://hips.hearstapps.com/amv-prod-tpw.s3.amazonaws.com/wp-content/uploads/2010/07/4101480755_98f352e3361.jpg?crop=0.666xw:1xh;center,top&resize=640:*',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Potato Hash',
        description: "This potato and onion hash is hearty and no-nonsense, substantial comfort food at its simple best. Although I tend to cook it just for myself at home, I bet if you gave it to a tableful of people when they came round for supper, they would be weepingly grateful, fashionable dietary restrictions notwithstanding. I like a little Tabasco sprinkled over the egg.",
        ingredients: [
            '2 lbs russet or yukon gold potatoes, peeled and chopped',
            '½ large onion, chopped',
            '1 red bell pepper, chopped',
            'Bacon, chopped ',
            'Sage leaves, minced',
            '4 large eggs',
            'Fresh chives, minced',
            'Kosher salt',
            'Freshly ground pepper',
        ],
        instructions: [
            'Peel and chop 3 leftover baked potatoes (russet or Yukon golds) into ½” pieces. Also roughly chop ½ large white onion and red bell pepper.',
            'In a cast-iron skillet, cook a few slices of bacon (or desired meat) until crispy. Remove meat and set aside. ',
            'Add in the onions and red peppers and saute over medium heat for 3-5 minutes until softened and the onions develop color. ',
            'Add in the chopped potatoes and give a thorough toss, making sure the potatoes are evenly coated in fat. Press everything down into an even layer, and let sit over medium heat undisturbed for 2 minutes.',
            'Using a firm sharp spatula, dig under the potatoes and flip them before patting them back down into an even layer. Let sit undisturbed for another 2 minutes. Repeat this process about 4 times, until everything is cooked, crisp, and browned. ',
            'Before the final flip, add in a couple finely minced fresh sage leaves along with chopped bacon from earlier. ',
            'Give the hash a flip and thoroughly mix to combine before digging 4 small divots in the mixture. Crack in 4 eggs, one into each divot.',
            'Cover and cook over medium-low heat for 4-5 minutes, or until the whites are set and the yolks are still runny. ',
            'In addition to kosher salt and freshly ground pepper, finish the potato hash with fresh minced chives. ',
        ],
        imageURL: 'https://www.wellplated.com/wp-content/uploads/2020/06/Sweet-Potato-Hash-with-Eggs-and-Sausage.jpg',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Kimchi',
        description: "Kimchi, a staple in Korean cuisine, is a traditional side dish that is salted and fermented vegetables, such as napa cabbage and korean radish, made with a widely varying selection of seasonings including gochugaru (chili powder), spring onions, garlic, ginger, and jeotgal (salted seafood), etc.It is also used in a variety of soups.",
        ingredients: [
            'Napa Cabbage',
            '1 cup gochugaru',
            '1 cup onion, chopped',
            '15 cloves garlic',
            '¼ cup ginger, peeled',
            '2 Tbsp salt',
            '2 Tbsp sugar',
            '1 Tbsp oyster sauce',
            '1 Tbsp soy sauce',
            '¼ cup fish sauce',
            '2 Tbsp rice vinegar',
            '½ cup water',
            'Chives, sliced',
        ],
        instructions: [
            'Start by cutting the Napa cabbage into quarters lengthwise and soak in lightly salted water for 1 hour. ',
            'Into a blender goes 1 cup of gochugaru, 1 cup of chopped onion, 15 cloves of garlic, ¼ cup of peeled ginger,  2 tablespoons each of salt and sugar, 1 tablespoon of oyster sauce, 1 tablespoon of soy sauce, ¼ cup of fish sauce, 2 tablespoons of rice vinegar, ½ cup of water and then blending everything together until as smooth as possible. ',
            'Place the cabbage quarters on a rimmed baking sheet, using a spoon or a brush thoroughly coat the cabbage layer by layer with the paste. Try getting deep in each layer. ',
            'After each layer is covered, massage the paste all over the cabbage, covering as much as possible with the paste. Repeat with the rest of the cabbage quarters. ',
            'Once covered, finely chop some chives and place them within each layer of the cabbage similar to the paste.',
            'Place some of the paste on the baking sheet and roll the cabbage quarters like a log in the paste and covering completely. ',
            'Once the cabbage has been rolled in the paste, cut the cabbage in half (depending on the size of the jar) and cover the newly exposed areas with the paste.',
            'Carefully layer the pieces of cabbage into the jar making sure the layers of the cabbage stay together. Jam in any remaining pieces of cabbage to the top and then top it with leftover paste.',
            'Place a paper towel over the jar and give it a few taps to make sure everything is settled.',
            'Let it sit at room temperature for 2 days before refrigerating for 2 weeks',
        ],
        imageURL: 'https://static01.nyt.com/images/3019/03/22/dining/jm-kimchi/merlin_150934050_507fb4e7-4773-4be3-96eb-9eae98f7b9e6-articleLarge.jpg',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Classic French Toast',
        description: "French toast will always be a staple for leisurely weekend breakfasts along with my favourite fluffy Pancakes and Pancakes bursting with Blueberries. So skip the bistro queue and make brunch at home this weekend!",
        ingredients: [
            'Thick slices of bread (white country loaf, challah, french brioche, or chocolate babka)',
            '1 ½ cups whole milk',
            '2 large eggs',
            '3-4 Tbsp granulated white sugar',
            '1-2 tsp real vanilla extract',
            '½ tsp ground cinnamon',
            '½ tsp nutmeg',
        ],
        instructions: [
            'Start by cutting your bread of choice into thick slices. Place onto a wire rack set in a rimmed baking sheet. Leave out overnight uncovered, or preheat the oven to its lowest temperature and place the bread in for 15-20 minutes, flipping halfway through. Either way, your bread should be nice and dry.',
            'For the classic custard, in a large bowl combine 1 ½ cups of whole milk, 2 large eggs, 3-4 tablespoons of granulated white sugar, 1-2 teaspoons of real vanilla extract, and ½ teaspoon each of ground cinnamon and nutmeg. Whisk together until combined and no streaks of egg remain.',
            'For fancy french toast custard, in a large bowl combine 1 ½ cups of half & half or heavy cream, 3-4 egg yolks, 3-4 tablespoons of dark brown sugar, 1-2 teaspoons of vanilla paste or one scraped vanilla bean, ½ teaspoon of freshly grated nutmeg, the zest of a lemon or orange, and a splash of either bourbon, rum, or brandy. Whisk together until fully combined. ',
            'Once the custard is ready, pour it into a cake pan or pie plate. Grab a piece of thickly cut bread and drop it into the custard, letting it sit for 20-30 seconds on each side.',
            'Heat 2 tablespoons of melted butter in a non-stick skillet over medium heat. Add the soaked bread to the skillet and let the bread fry for 3-5 minutes on each side, until golden brown. ',
            'Place onto a wire rack set in a rimmed baking sheet in a 350°F oven while you cook all of the pieces.',
            'Once every piece of toast is complete, stack on a plate, topped with butter and maple syrup. ',
            'For a tangy butter for the chocolate babka, whip together 8 ounces of room temperature cream cheese with 3 tablespoons of sugar and a pinch of salt.',
        ],
        imageURL: 'https://d1e3z2jco40k3v.cloudfront.net/-/media/mccormick-us/recipes/mccormick/q/800/quick_and_easy_french_toast_new_800x800.jpg?rev=7ec5983cd3674050aac15327c66935dc&vd=20200628T071104Z&hash=E2A73229EE45D0D9AD547240FE366160',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Potato Gnocchi',
        description: "The dough for gnocchi is most often rolled out before it is cut into small pieces about the size of a wine cork.[17] The little dumplings are then pressed with a fork or a cheese grater to make ridges that can hold sauce. Alternatively, they are simply cut into little lumps.",
        ingredients: [
            '4 large potatoes',
            '1 egg',
            'All-purpose flour',
        ],
        instructions: [
            'Start by poking the potatoes all over using a fork. Place them in a preheated 375°F oven for about an hour. After this, the skins should be crisp and the interior should easily pierce with a knife. ',
            'Using a clean dish towel, grab each potato, and remove the skin from the potato. This will allow more steam to escape. Less steam means less moisture, and less moisture means lighter, fluffier gnocchi. Cover with plastic wrap and let cool for a few hours. ',
            'Once they have cooled down, pass them through the fine holes of a cheese grater (for an easier and faster method use a potato ricer). Once the potatoes are grated down to fluffy little bits, place them onto a rimmed baking sheet and measure to 500 grams. Add one beaten egg yolk spread evenly across (1 beaten egg yolk for every 500 grams). Then sift 100 grams of all-purpose flour across the potatoes.',
            'Bring the potatoes into a ball of dough using a bench scraper (or the desired tool) to chop and mix everything up to make sure the egg and flour are evenly distributed. Start using your hands to press it into one cohesive mass.',
            'Once the mass has formed, start kneading for about 90 seconds for slightly toothsome gnocchi. A phrase to remember, “The more you knead the tougher they’ll bead, but if early on you surrender then they’ll be tender”. ',
            'Once the dough is smooth and no egg or flour streaks remain, roll it out into a fat little log and cut into four even pieces. Sift some all-purpose flour onto a work surface then roll each piece of dough into a 1” thick rope. Press down any pudgy spots until it is nice and even. ',
            'Then using a bench scraper or sharp knife, cut into little dumplings or into the desired size. ',
            'For different shapes other than the pillow-like shape, roll a piece of dough between your hands until round or simply make a dent in the center using your finger. For a classic gnocchi shape, press down against the tines of a fork using your thumb down and across the fork. ',
            'Once all of the dough has been cut and shaped into the desired gnocchi shape, place onto a rimmed baking sheet and cover with a dusting of all-purpose flour. For non-immediate cooking, place in a freezer to solidify for 1 hour, then scrape off and place in a bag and back into the freezer.',
        ],
        imageURL: 'https://www.thecuriouschickpea.com/wp-content/uploads/2018/02/shapedgnocchi-1-768x1152.jpg.webp',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Nashville Hot Chicken',
        description: "This week on Basics, it's time you learned how to make that classic Nashville hot chicken. If you've never had it, it's just spicy fried chicken. And it's delicious.",
        ingredients: [
            '1 whole chicken',
            'Kosher salt',
            'Freshly ground pepper',
            '1 cup whole milk',
            'Louisiana hot sauce',
            '2 large eggs',
            '2 cups all-purpose flour',
            '1 cup lard',
            '1 cup vegetable oil',
            '3 Tbsp cayenne pepper',
            '1 Tbsp light brown Sugar',
            '½ tsp garlic powder',
            '½ tsp paprika',
            'Wonder bread, for serving',
            'Pickle chips, for serving',
        ],
        instructions: [
            'Start by cutting out the spine and placing a little snip at the base of the breast bone to easily crack it in half.',
            'Cut the bird in half, separating into two pieces. Make shallow cuts around the base of the drumette to expose the joint, then crack open and run the knife in between to separate the drumettes. ',
            'There is very little bone between the breast and thigh so separating should be easy. To separate the drumstick, place shallow cuts around where the bones meet, then crack open and run the knife between to separate the drumstick from the thigh. ',
            'Cut the chicken breasts in half. Rinse and repeat the steps on the other half of the chicken. You should have 10 pieces.',
            'Once the chicken has been cut into pieces, dry brine them by generously coating both sides with kosher salt and freshly ground pepper.  Place into a food-safe container and cover tightly with plastic wrap and put in the fridge for at least 4 hours. ',
            'Make the breading: combine 1 cup of whole milk with a few dashes of Louisiana hot sauce and 2 large eggs. Beat together with a fork until no streaks remain. For the dry ingredients, combine 2 cups of all-purpose flour, 2 teaspoons of kosher salt, and a few tablespoons of the egg/milk mixture. This will create little chunks of breading which will help with crispiness. ',
            'First, the chicken goes into the flour mixture, then into the egg mixture, and then back into the flour mixture. This is commonly known as double-dipped fried chicken. Repeat with the remaining chicken and let it hang out in the flour while you prepare oil for frying. ',
            'In a high walled frying pan or skillet, place a big block of lard (about 1 cup) and 1 cup of vegetable oil. Heat over medium-high heat and bring it to 350°F. ',
            'Gently lay the chicken pieces into the oil -making sure to place them going away from you to ensure no self-splattering. Fry for 5-7 minutes per side, or until deeply golden brown and crisp.',
            'Place on a wire rack set in a rimmed baking sheet and keep in a 325°F oven until they are thoroughly cooked through. ',
            'To prepare the spice mixture, in a small bowl goes 3 tablespoons of cayenne pepper, 1 tablespoon of light brown sugar, 1 teaspoon of freshly ground pepper, and ½ teaspoon each of garlic powder, paprika, and kosher salt. For a tame and less spicy version, you can reduce the cayenne pepper. Whisk to combine. Put the spice mix in a heat-proof bowl.',
            'Add ½ cup of the frying oil then mix completely together.',
            'Generously brush down both sides of the chicken with the spice oil. If applied while the oil and the chicken are still hot, it’s going to absorb into the crust without making it soggy.',
            'For the proper Nashville style, place on a piece of wonder bread topped with pickle chips. ',
        ],
        imageURL: 'https://assets.bonappetit.com/photos/57ad4431f1c801a1038bcb17/master/w_1024%2Cc_limit/nashville-style-hot-chicken.jpg',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Chewy, Fudgy Brownies',
        description: "The BEST brownie recipe! With crispy edges, fudgy middles, and rich chocolate flavor, these homemade brownies will disappear in no time.",
        ingredients: [
            '⅓ cup cocoa powder',
            '1 ½ tsp espresso powder',
            '2 ounces unsweetened chocolate, chopped',
            '½ cup plus 2 Tbsp boiling water',
            '4 Tbsp butter',
            '½ cup plus 2 Tbsp vegetable oil',
            '2 large eggs plus 2 egg yolks',
            '1 ½ tsp vanilla extract',
            '2 ½ cups granulated sugar',
            '1 ¾ cup all purpose flour',
            '6 ounces bittersweet chocolate, chopped',
        ],
        instructions: [
            'Prepare your baking dish by lining with aluminum foil or parchment paper and greasing with cooking spray.',
            'In a large bowl, combine cocoa powder, espresso powder, chopped unsweetened chocolate, and boiling water. Stir to combine and get everything melted.',
            'While still warm, add butter and stir until melted. Add vegetable oil and stir again.',
            'Once the mixture has cooled, add the eggs and egg yolks and stir to combine.',
            'Add vanilla extract and whisk, then add granulated sugar and stir to combine.',
            'Next, add flour. Mix it thoroughly and then add the chopped bittersweet chocolate. Stir to combine one last time.',
            'Pour batter into prepared pan. Bake at 350°F for 30-35 minutes, until a tester comes out clean-ish.',
            'Let brownies cool for one hour in the pan. ',
            'Remove them from pan using parchment or foil. Serve and enjoy! ',
        ],
        imageURL: 'https://i0.wp.com/smittenkitchen.com/wp-content/uploads//2012/08/my-favorite-brownies1.jpg?fit=750%2C500&ssl=1',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Risotto',
        description: "The best risotto is rich and creamy, with supple grains of rice, perfumed of wine and Parmesan, and replete with butter. It is the kind of dish best served in a deep bowl with a large spoon for bite after bite of creamy comfort.",
        ingredients: [
            'White onion',
            'Risotto rice (like arborio or carnaroli)',
            'Dry white wine',
            'Chicken stock',
            'Parmesan',
            'Salt and pepper',
            'Chives (garnish)',
        ],
        instructions: [
            'Set your pressure cooker to its hottest or “browning” setting. Add one diced white onion to the pressure cooker and stir, sweating the onions.',
            'Add 2 cups of risotto rice to the pressure cooker (recommended: arborio or carnaroli rice). Stir to toast the rice for one minute, until edges become translucent.',
            'Deglaze with ½ cup of white wine. Continue to saute until all of the alcohol has cooked off.',
            'Next, add 4 cups of chicken stock. Stir and make sure no rice is stuck to the sides of the pressure cooker.',
            'Lock the lid on your pressure cooker and cook on high for 5-6 minutes. Make sure to let steam escape through the quick-release steam valve before opening cooker.',
            'Grate a lot of parmesan (a lot!) into the risotto and season with salt and pepper. Stir.',
            'Serve garnished with more parmesan and chives for garnish.',
        ],
        imageURL: 'https://www.thespruceeats.com/thmb/5mExmaXLqLawTKT7s34NK3xVOzg=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/risotto-recipe-for-beginners-996008-hero-01-9ca07ec80a024c80909e0c8a92f0674c.jpg',
        author: 'Carlos Cusiter',
    },
    {
        title: 'Pasta Al Limone',
        description: "What's better than pasta aglio olio? Very few things, but one of them is its saucy cousin, pasta al limone. Traditionally a creamy emulsion of oil, lemon, and pasta water, this simple but indulgent dish can be amped up a number of ways. Let's lemon! Or something..",
        ingredients: [
            '1 clove garlic, peeled and sliced',
            'Parsley, chopped',
            '1 large lemon',
            'Pasta',
            'Olive oil',
            '1 tsp chili flakes',
            'Freshly ground black pepper',
            'Kosher salt',
            '2-3 oz parmesan cheese, grated',
        ],
        instructions: [
            'Start by peeling and thinly slicing 1 large clove of garlic. Then, roughly or finely chop some fresh parsley and roll 1 large lemon along a work surface before cutting it in half. ',
            'For homemade pasta, in a large amount of all-purpose flour shaped into a crater, crack in 3 eggs, a pinch of salt and begin mixing it until a slurry forms. Toss it together until a ball of dough forms. Knead continuously for 7-10 minutes. Wrap in plastic wrap and let sit at room temperature for 30 minutes. ',
            'To roll out, generously flour the dough and work surface before rolling the dough out with a roller to a thickness of 1 ml. Generously flour and fold like an accordion, making sure that each fold does not overlap. ',
            'Using a sharp knife, slice the dough into the desired size before unfolding and twisting into nests to prevent pasta kinks.  ',
            'In a sauce pot, bring just enough water to cover the pasta to a boil before adding in the pasta. Make sure to stir after adding the pasta to ensure no sticking. ',
            'For the Al Limone sauce, add 2-3 tablespoons of olive oil to a high-walled saute pan. In addition, add the sliced garlic from earlier, 1 teaspoon of chili flakes, the zest of 1 lemon, and some freshly ground black pepper. Cook for 3-5 minutes. ',
            'Once the garlic is a light blonde, dump in the pasta if using store-bought (1-2 minutes shy of being done), and if using fresh pasta only boil for 30 seconds before adding. ',
            'Once pasta is added, give everything a toss to fully incorporate everything. ',
            'Over medium-low heat add the juice of either ½ a lemon or the juice of 1 whole lemon, a small pour of olive oil, ¼ cup of freshly chopped parsley, and 2-3 ounces of freshly grated parmesan cheese. Stir together until combined. ',
            'After everything has been combined, add in ¼ cup of boiling pasta water and toss together. Add a splash at a time as necessary, checking to see if it’s too thick or thin. If too thick, add more pasta water. If too thin, add more cheese. Season with kosher salt.',
            'Once the sauce has reached the desired consistency, twist up and serve. Garnish with extra grated Parmigiano Reggiano, chopped parsley, and grated lemon zest. ',
        ],
        imageURL: 'https://i2.wp.com/smittenkitchen.com/wp-content/uploads//2019/06/simplest-spaghetti-al-limone.jpg?fit=750%2C500&ssl=1',
        author: 'Carlos Cusiter',
    },
]

module.exports = recipes;